[package]
name = "schematools"
description = "Tools for codegen, preprocessing and validation of json-schema and openapi spec"
edition = "2021"
license.workspace = true
readme = "../../README.md"
repository.workspace = true
version.workspace = true

[features]
default = ["codegen", "git", "http", "json-patch", "fs4"]
codegen = ["tera", "semver", "pluralizer"]
git = ["gix"]
http = ["jsonschema/resolve-http", "reqwest"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
yaml_serde = { workspace = true }
reqwest = { workspace = true, optional = true }
log = { workspace = true }
thiserror = { workspace = true }

url = "2"
regex = "1"
jsonschema = { version = "0.49", default-features = false, features = ["resolve-file", "tls-aws-lc-rs"] }
tera = { version = "2", optional = true }
walkdir = "2"
json-patch = { version = "4.2", optional = true }
semver = { version = "1.0", optional = true }
gix = { version = "0.86", default-features = false, optional = true, features = ["basic", "extras", "comfort", "sha1", "blocking-network-client", "blocking-http-transport-reqwest-rust-tls"] }
fs4 = { version = "1.1", optional = true }
md5 = { package = "md-5", version = "0.11" }
cruet = "1"
digest = "0.11"
pluralizer = { version = "0.5", optional = true }

[dev-dependencies]
serial_test = "4.0"
test-case = "3.3"
testing_logger = "0.1.1"
